version: '3'

services:
        adminer:
                image: adminer
       

                networks: 
                        - 'wp-net'
                ports:
                        - '8080:8080'

        mysql:
                image: mysql:latest
                container_name: mysql
                command: '--default-authentication-plugin=mysql_native_password'
                networks: 
                        wp-net:
                                aliases:
                                        - mysql
                volumes:
                        - 'wp_db:/var/lib/mysql:rw'

                environment:
                     - "MYSQL_ROOT_PASSWORD=secret" 
                     - "MYSQL_DATABASE=wordpress" 
                     - "MYSQL_USER=wp_user" 
                     - "MYSQL_PASSWORD=start123" 

        wordpress:
                image: wordpress:latest
                container_name: wordpress
                depends_on:
                        - mysql
                networks: 
                        - 'wp-net'
                ports:
                        - '80:80'
                environment: 
                        - "WORDPRESS_DB_HOST=mysql"
                        - "WORDPRESS_DB_USER=wp_user"
                        - "WORDPRESS_DB_PASSWORD=start123"
                        - "WORDPRESS_DB_NAME=wordpress" 
                volumes: 
                        - 'wp_wp:/var/www/html:rw'

volumes:
        wp_db:
        wp_wp: 
networks:
        wp-net:
